#!/usr/bin/env bash
if [ $(uname) = "Linux" ]; then
    python3 python/rpm_builder.py --list
elif [ $(uname) = "Darwin" ]; then
    /Users/christian/Applications/python/bin/python3 python/mac_builder.py --list
else
    echo "Unknown operating system"
fi
